# Dockerfile.nginx
FROM nginx:alpine

# Удаляем стандартные файлы
RUN rm -rf /usr/share/nginx/html/*

# Копируем свою статику внутрь образа
COPY static /static

# Копируем свой конфиг
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80